name: GCP Infra Provisioning (geni-project)

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform Action (apply or destroy)"
        required: true
        default: "apply"

jobs:
  provision:
    runs-on: ubuntu-latest

    env:
      TF_VAR_project_id: geni-project
      TF_VAR_region: asia-south1
      GOOGLE_PROJECT: geni-project

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Show Terraform Action
      run: echo " Running Terraform action: ${{ github.event.inputs.action }} on project: ${{ env.GOOGLE_PROJECT }}"

    - name:  Authenticate to Google Cloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: geni-project
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: ðŸ” Set GOOGLE_APPLICATION_CREDENTIALS from base64
      run: |
        echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 -d > /tmp/key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/key.json" >> $GITHUB_ENV

    - name: Verify GCloud Authentication
      run: gcloud auth list && gcloud config list project

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init
      working-directory: .

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: .

    - name: Terraform Apply
      if: github.event.inputs.action == 'apply'
      run: terraform apply -auto-approve
      working-directory: .

    - name: List Terraform Resources
      if: github.event.inputs.action == 'apply'
      run: terraform state list

    - name: Show Terraform State
      if: github.event.inputs.action == 'apply'
      run: terraform show
      working-directory: .

    - name: Activate Service Account (Apply)
      if: github.event.inputs.action == 'apply'
      run: |
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      run: terraform destroy -auto-approve
      working-directory: .

    - name: Activate Service Account (Destroy)
      if: github.event.inputs.action == 'destroy'
      run: |
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS